### ISSUE TITLE
Script para instalar servicios base a nivel OS

### ISSUE THREAD

**Issue by rodowi** [mxabierto/cluster#4]
El OS: Ubuntu 14.04 LTS

Requerimientos para cluster a nivel OS
1.- Actualizar kernel a 4.2.2
2.- Instalar y configurar etcd 2.2.0
3.- Instalar y configurar fleet 0.11.5
4.- Instalar y configurar flanneld 0.5.4
5.- Instalar Docker 1.8.3

**Comment by rodowi** [comment]
## Instrucciones

**Instalación**: Se coloca el binario estáticamente compilado en el PATH
**Configuración**: Se carga el unit file correspondiente utilizando systemd
**Correr aplicaciones**:
- Crear una imagen docker por aplicación
- Crear un unit file / service description por aplicación
- Correr la aplicación en el cluster utilizando fleet; i.e.: fleet run buda-front.service

**Comment by rodowi** [comment]
@bcessa este issue lo cierra https://github.com/mxabierto/cluster/commit/2bc037d19ad11eab25421133bcc15f5104d3ad77?

**Comment by bcessa** [comment]
Si, justo todos esos componentes ya se instalan y configuran en ese setup de muestra; usando Ubuntu como base
